In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("../data/processed/combined.csv")
dfNorm = pd.read_csv("../data/processed/combinedNorm.csv")
dfSimAgg = pd.read_csv("../data/aggregated/simAgg.csv")
dfSimAggNorm = pd.read_csv("../data/aggregated/simAggNorm.csv")
dfAdvAgg = pd.read_csv("../data/aggregated/advAgg.csv")
dfAdvAggNorm = pd.read_csv("../data/aggregated/advAggNorm.csv")

In [3]:
def simple_summarize(df):
    au_cols = [c for c in df.columns if c.startswith("AU")]

    summary = pd.DataFrame({
        "Min": df[au_cols].min(),
        "Mean": df[au_cols].mean(),
        "Max": df[au_cols].max(),
        "Std": df[au_cols].std(),
    })

    return summary.round(3)

In [4]:
def advanced_summarize(df):
    au_cols = [c for c in df.columns if c.startswith("AU")]

    grouped = df.groupby("source_id")[au_cols]

    summary = pd.concat({
        "Min": grouped.min(),
        "Mean": grouped.mean(),
        "Max": grouped.max(),
        "Std": grouped.std(),
        "Median": grouped.median(),
        "Q25": grouped.quantile(0.25),
        "Q85": grouped.quantile(0.85)
    }, axis=1)

    summary = (
        summary
        .stack(level=1, future_stack=True)
        .rename_axis(index=["source_id", "Action Unit"])
    )

    summary["IQR (Q85 - Q25)"] = (
        summary["Q85"] - summary["Q25"]
    )

    return summary.round(3)

In [11]:
simple_summarize(df)

        Min   Mean   Max    Std
AU01_r  0.0  0.377  5.00  0.697
AU02_r  0.0  0.125  3.48  0.301
AU04_r  0.0  0.785  4.11  0.780
AU05_r  0.0  0.074  2.34  0.200
AU06_r  0.0  0.494  3.15  0.553
AU07_r  0.0  1.059  4.54  0.903
AU09_r  0.0  0.107  3.20  0.235
AU12_r  0.0  0.318  2.78  0.443

In [6]:
advanced_summarize(df)

                       Min   Mean   Max    Std  Median    Q25    Q85  \
source_id Action Unit
Art6      AU01_r       0.0  0.326  3.97  0.629    0.02  0.000  0.740
          AU02_r       0.0  0.138  2.64  0.332    0.00  0.000  0.260
          AU04_r       0.0  0.686  2.93  0.745    0.47  0.020  1.430
          AU05_r       0.0  0.070  2.27  0.187    0.00  0.000  0.130
          AU06_r       0.0  0.692  3.07  0.612    0.67  0.060  1.340
...                    ...    ...   ...    ...     ...    ...    ...
Tech21    AU05_r       0.0  0.029  0.43  0.063    0.00  0.000  0.073
          AU06_r       0.0  0.287  1.36  0.276    0.23  0.038  0.570
          AU07_r       0.0  1.395  2.54  0.431    1.40  1.100  1.823
          AU09_r       0.0  0.038  0.67  0.082    0.00  0.000  0.080
          AU12_r       0.0  0.191  1.71  0.340    0.02  0.000  0.423

                       IQR (Q85 - Q25)
source_id Action Unit
Art6      AU01_r                 0.740
          AU02_r                 0.260
          AU04_r                 1.410
          AU05_r                 0.130
          AU06_r                 1.280
...                                ...
Tech21    AU05_r                 0.073
          AU06_r                 0.532
          AU07_r                 0.723
          AU09_r                 0.080
          AU12_r                 0.423

[80 rows x 8 columns]

In [7]:
simple_summarize(dfNorm)

          Min   Mean     Max    Std
AU01_r -0.093  0.375   5.338  0.692
AU02_r  0.000  0.478  11.600  1.131
AU04_r -0.882  0.169   2.915  0.535
AU05_r  0.000  0.570  21.262  1.555
AU06_r -0.895  0.181  12.250  0.869
AU07_r -1.935  0.054   4.539  0.543
AU09_r  0.000  0.412  18.824  0.883
AU12_r -0.716  0.176  18.500  0.724

In [8]:
simple_summarize(dfSimAgg)

          Min   Mean    Max    Std
AU01_r  0.048  0.311  1.207  0.219
AU02_r  0.028  0.106  0.250  0.051
AU04_r  0.000  0.786  2.765  0.579
AU05_r  0.006  0.062  0.164  0.031
AU06_r  0.000  0.428  1.517  0.367
AU07_r  0.029  1.065  2.587  0.607
AU09_r  0.020  0.095  0.280  0.054
AU12_r  0.000  0.305  1.392  0.310

In [9]:
simple_summarize(dfSimAggNorm)

          Min   Mean    Max    Std
AU01_r  0.018  0.326  0.928  0.193
AU02_r  0.111  0.426  0.926  0.174
AU04_r -0.350  0.177  1.066  0.308
AU05_r  0.060  0.486  1.368  0.242
AU06_r -0.744  0.162  5.380  0.670
AU07_r -0.904  0.069  1.662  0.366
AU09_r  0.091  0.385  1.000  0.192
AU12_r -0.600  0.201  2.520  0.423