In [1]:
from src.preprocessing.utils import quality_filter, normalize_by_speaker
from src.preprocessing.cleaning import drop_all
from src.preprocessing.loading import load_df
from src.preprocessing.aggregating import simple_aggregation, advanced_aggregation

# 0. LOADING AND CLEANING THE DATA

In [2]:
df = load_df()
df = drop_all(df)
df = quality_filter(df)

===== Loading Data
===== Dropping unnecessary features
===== Start Filtering for Confidence
Before filtering: 23369 frames
After filtering: 23123 frames
===== Finished Filtering

In [3]:
df = df.drop(columns=["confidence", "success", "duration"])

# 1. COMBINING DATA INTO ONE DATAFRAME
## 1.1 Combining Raw Data

In [4]:
df

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,AU09_r,AU12_r,clip_id,label,source_id,appraisal
0,0.00,0.00,0.00,0.00,0.87,0.16,0.00,0.0,Art6_S2,1,Art6,Appreciation
1,0.00,0.00,0.00,0.00,1.10,0.42,0.00,0.0,Art6_S2,1,Art6,Appreciation
2,0.00,0.00,0.00,0.00,1.31,0.62,0.00,0.0,Art6_S2,1,Art6,Appreciation
3,0.00,0.00,0.00,0.00,1.54,1.06,0.00,0.0,Art6_S2,1,Art6,Appreciation
4,0.04,0.00,0.00,0.00,1.67,1.25,0.00,0.0,Art6_S2,1,Art6,Appreciation
...,...,...,...,...,...,...,...,...,...,...,...,...
23364,0.33,0.38,0.81,0.23,0.01,1.34,0.05,0.0,Tech21_S6,0,Tech21,NaN
23365,0.23,0.24,0.90,0.23,0.02,1.35,0.14,0.0,Tech21_S6,0,Tech21,NaN
23366,0.12,0.12,0.90,0.27,0.06,1.54,0.19,0.0,Tech21_S6,0,Tech21,NaN
23367,0.02,0.05,0.86,0.17,0.14,1.56,0.22,0.0,Tech21_S6,0,Tech21,NaN
23368,0.00,0.00,0.77,0.03,0.25,1.32,0.17,0.0,Tech21_S6,0,Tech21,NaN

In [5]:
df.to_csv("../data/processed/combined.csv")

## 1.2 Normalizing Data (SPEAKER-NORMALIZED)
### Soft Cap -> min. IQR value is 0.01

In [6]:
df_norm = normalize_by_speaker(df, debug=True)

4 IQR value(s) were transformed to 0.1:
['AU12_r', 'AU12_r', 'AU05_r', 'AU09_r']

In [7]:
df_norm

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,AU09_r,AU12_r,clip_id,label,source_id,appraisal
0,-0.027027,0.000000,-0.333333,0.0,0.156250,-0.367716,0.0,0.000000,Art6_S2,1,Art6,Appreciation
1,-0.027027,0.000000,-0.333333,0.0,0.335938,-0.205672,0.0,0.000000,Art6_S2,1,Art6,Appreciation
2,-0.027027,0.000000,-0.333333,0.0,0.500000,-0.081022,0.0,0.000000,Art6_S2,1,Art6,Appreciation
3,-0.027027,0.000000,-0.333333,0.0,0.679688,0.193207,0.0,0.000000,Art6_S2,1,Art6,Appreciation
4,0.027027,0.000000,-0.333333,0.0,0.781250,0.311624,0.0,0.000000,Art6_S2,1,Art6,Appreciation
...,...,...,...,...,...,...,...,...,...,...,...,...
23364,1.107143,3.454545,1.403846,2.3,-0.413146,-0.082930,0.5,-0.047226,Tech21_S6,0,Tech21,NaN
23365,0.750000,2.181818,1.576923,2.3,-0.394366,-0.069109,1.4,-0.047226,Tech21_S6,0,Tech21,NaN
23366,0.357143,1.090909,1.576923,2.7,-0.319249,0.193504,1.9,-0.047226,Tech21_S6,0,Tech21,NaN
23367,0.000000,0.454545,1.500000,1.7,-0.169014,0.221147,2.2,-0.047226,Tech21_S6,0,Tech21,NaN
23368,-0.071429,0.000000,1.326923,0.3,0.037559,-0.110574,1.7,-0.047226,Tech21_S6,0,Tech21,NaN

In [8]:
df_norm.to_csv("../data/processed/combinedNorm.csv")

# 2. AGGREGATING DATA PER CLIP-ID (SIMPLE AGGREGATION)
## 2.1 Raw Data

In [9]:
df_simAgg = simple_aggregation(df)

In [10]:
df_simAgg

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,AU09_r,AU12_r,label,source_id
clip_id,,,,,,,,,,
Art6_S2,0.217560,0.179464,0.253452,0.069881,0.721845,0.590000,0.089345,0.144940,1,Art6
Art6_S32,0.281684,0.111053,0.234947,0.057789,0.586105,0.775158,0.103263,0.019263,1,Art6
Art6_S36,0.176599,0.135476,0.436905,0.053095,1.178333,0.830884,0.092177,0.035816,1,Art6
Art6_S43,0.339930,0.103427,0.470839,0.049790,0.508322,0.835664,0.061049,0.000420,0,Art6
Art6_S6,0.076600,0.071600,0.618600,0.021800,0.602000,1.872200,0.036400,0.000000,0,Art6
...,...,...,...,...,...,...,...,...,...,...
Tech21_S32,0.278000,0.060800,0.060400,0.006000,0.275600,1.212800,0.028400,0.653200,0,Tech21
Tech21_S33,0.122174,0.056957,0.358551,0.024783,0.287681,1.130145,0.097826,0.367826,0,Tech21
Tech21_S4,0.070357,0.037857,0.059286,0.017857,0.406429,1.712143,0.027857,0.203571,0,Tech21
Tech21_S5,0.100690,0.027931,0.045862,0.017586,0.403103,2.010690,0.027586,0.237241,0,Tech21
Tech21_S6,0.148816,0.070526,0.383158,0.038947,0.200921,1.521053,0.019868,0.093158,0,Tech21

In [11]:
df_simAgg.to_csv("../data/aggregated/simAgg.csv")

## 2.2 Normalized Data (SPEAKER-NORMALIZED)

In [12]:
df_simAgg_norm = simple_aggregation(df_norm)

In [13]:
df_simAgg_norm

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,AU09_r,AU12_r,label,source_id
clip_id,,,,,,,,,,
Art6_S2,0.266972,0.690247,-0.153580,0.537546,0.040504,-0.099720,0.297817,1.449405,1,Art6
Art6_S32,0.353627,0.427126,-0.166704,0.444534,-0.065543,0.015680,0.344211,0.192632,1,Art6
Art6_S36,0.211620,0.521062,-0.023472,0.408425,0.397135,0.050411,0.307256,0.358163,1,Art6
Art6_S43,0.432338,0.397795,0.000595,0.383002,-0.126311,0.053390,0.203497,0.004196,0,Art6
Art6_S6,0.076486,0.275385,0.105390,0.167692,-0.053125,0.699408,0.121333,0.000000,0,Art6
...,...,...,...,...,...,...,...,...,...,...
Tech21_S32,0.921429,0.552727,-0.037692,0.060000,0.085634,-0.258742,0.284000,1.495159,0,Tech21
Tech21_S33,0.364907,0.517787,0.535674,0.247826,0.108321,-0.372986,0.978261,0.821313,0,Tech21
Tech21_S4,0.179847,0.344156,-0.039835,0.178571,0.331321,0.431434,0.278571,0.433463,0,Tech21
Tech21_S5,0.288177,0.253918,-0.065650,0.175862,0.325077,0.844077,0.275862,0.512967,0,Tech21
Tech21_S6,0.460056,0.641148,0.582996,0.389474,-0.054608,0.167315,0.198684,0.172746,0,Tech21

In [14]:
df_simAgg_norm.to_csv("../data/aggregated/simAggNorm.csv")

# 3. AGGREGATING DATA PER CLIP-ID (ADVANCED AGGREGATION)
## 3.1 Raw Data

In [15]:
df_advAgg = advanced_aggregation(df)

In [16]:
df_advAgg

,AU01_r_mean,AU01_r_std,AU01_r_q95,AU02_r_mean,AU02_r_std,AU02_r_q95,AU04_r_mean,AU04_r_std,AU04_r_q95,AU05_r_mean,...,AU07_r_std,AU07_r_q95,AU09_r_mean,AU09_r_std,AU09_r_q95,AU12_r_mean,AU12_r_std,AU12_r_q95,label,source_id
clip_id,,,,,,,,,,,,,,,,,,,,,
Art6_S2,0.217560,0.346387,1.0600,0.179464,0.466050,1.0245,0.253452,0.364526,1.1665,0.069881,...,0.594709,1.9840,0.089345,0.163360,0.4860,0.144940,0.445952,1.539,1,Art6
Art6_S32,0.281684,0.438944,1.1990,0.111053,0.264034,0.5700,0.234947,0.280425,0.7430,0.057789,...,0.733305,1.8960,0.103263,0.189329,0.5860,0.019263,0.081870,0.103,1,Art6
Art6_S36,0.176599,0.260498,0.7735,0.135476,0.332685,1.0700,0.436905,0.333330,1.1235,0.053095,...,0.676368,2.1480,0.092177,0.164926,0.4800,0.035816,0.143095,0.207,1,Art6
Art6_S43,0.339930,0.533242,1.3790,0.103427,0.217347,0.6300,0.470839,0.472517,1.2100,0.049790,...,0.557414,1.7370,0.061049,0.106584,0.3100,0.000420,0.002876,0.000,0,Art6
Art6_S6,0.076600,0.136361,0.3710,0.071600,0.156014,0.4110,0.618600,0.406523,1.3645,0.021800,...,0.670334,3.1185,0.036400,0.049683,0.1255,0.000000,0.000000,0.000,0,Art6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tech21_S32,0.278000,0.361813,0.9420,0.060800,0.115575,0.3300,0.060400,0.066551,0.1820,0.006000,...,0.200510,1.4580,0.028400,0.048017,0.1400,0.653200,0.423101,1.306,0,Tech21
Tech21_S33,0.122174,0.182530,0.5120,0.056957,0.108048,0.2960,0.358551,0.324324,0.9140,0.024783,...,0.405446,1.6700,0.097826,0.174127,0.5400,0.367826,0.354014,1.136,0,Tech21
Tech21_S4,0.070357,0.094418,0.2730,0.037857,0.082971,0.2015,0.059286,0.099552,0.2600,0.017857,...,0.365466,2.2995,0.027857,0.039661,0.0995,0.203571,0.125114,0.393,0,Tech21
Tech21_S5,0.100690,0.152689,0.4600,0.027931,0.051919,0.1100,0.045862,0.097816,0.2300,0.017586,...,0.269854,2.4640,0.027586,0.051036,0.1600,0.237241,0.145820,0.470,0,Tech21
Tech21_S6,0.148816,0.232276,0.7075,0.070526,0.160066,0.4300,0.383158,0.327517,0.8925,0.038947,...,0.321345,2.2525,0.019868,0.042599,0.0950,0.093158,0.149231,0.440,0,Tech21

In [17]:
df_advAgg.to_csv("../data/aggregated/advAgg.csv")

## 3.2 Normalized Data (SPEAKER-NORMALIZED)

In [18]:
df_advAgg_norm = advanced_aggregation(df_norm)

In [19]:
df_advAgg_norm

,AU01_r_mean,AU01_r_std,AU01_r_q95,AU02_r_mean,AU02_r_std,AU02_r_q95,AU04_r_mean,AU04_r_std,AU04_r_q95,AU05_r_mean,...,AU07_r_std,AU07_r_q95,AU09_r_mean,AU09_r_std,AU09_r_q95,AU12_r_mean,AU12_r_std,AU12_r_q95,label,source_id
clip_id,,,,,,,,,,,,,,,,,,,,,
Art6_S2,0.266972,0.468090,1.405405,0.690247,1.792500,3.940385,-0.153580,0.258529,0.493972,0.537546,...,0.370651,0.769087,0.297817,0.544532,1.620000,1.449405,4.459518,15.390000,1,Art6
Art6_S32,0.353627,0.593167,1.593243,0.427126,1.015514,2.192308,-0.166704,0.198883,0.193617,0.444534,...,0.457030,0.714241,0.344211,0.631098,1.953333,0.192632,0.818697,1.030000,1,Art6
Art6_S36,0.211620,0.352025,1.018243,0.521062,1.279559,4.115385,-0.023472,0.236404,0.463475,0.408425,...,0.421544,0.871299,0.307256,0.549755,1.600000,0.358163,1.430954,2.070000,1,Art6
Art6_S43,0.432338,0.720597,1.836486,0.397795,0.835949,2.423077,0.000595,0.335119,0.524823,0.383002,...,0.347407,0.615145,0.203497,0.355280,1.033333,0.004196,0.028764,0.000000,0,Art6
Art6_S6,0.076486,0.184272,0.474324,0.275385,0.600052,1.580769,0.105390,0.288314,0.634397,0.167692,...,0.417784,1.476161,0.121333,0.165610,0.418333,0.000000,0.000000,0.000000,0,Art6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tech21_S32,0.921429,1.292188,3.292857,0.552727,1.050685,3.000000,-0.037692,0.127982,0.196154,0.060000,...,0.277139,0.080166,0.284000,0.480174,1.400000,1.495159,0.999058,3.036600,0,Tech21
Tech21_S33,0.364907,0.651893,1.757143,0.517787,0.982257,2.690909,0.535674,0.623700,1.603846,0.247826,...,0.560396,0.373186,0.978261,1.741270,5.400000,0.821313,0.835925,2.635183,0,Tech21
Tech21_S4,0.179847,0.337206,0.903571,0.344156,0.754279,1.831818,-0.039835,0.191446,0.346154,0.178571,...,0.505137,1.243262,0.278571,0.396613,0.995000,0.433463,0.295428,0.880756,0,Tech21
Tech21_S5,0.288177,0.545316,1.571429,0.253918,0.471990,1.000000,-0.065650,0.188108,0.288462,0.175862,...,0.372983,1.470629,0.275862,0.510361,1.600000,0.512967,0.344322,1.062574,0,Tech21
Tech21_S6,0.460056,0.829555,2.455357,0.641148,1.455143,3.909091,0.582996,0.629840,1.562500,0.389474,...,0.444154,1.178300,0.198684,0.425987,0.950000,0.172746,0.352375,0.991736,0,Tech21

In [20]:
df_advAgg_norm.to_csv("../data/aggregated/advAggNorm.csv")