In [1]:
import pandas as pd

from src.configuration.config import set_seed
from src.AggregationBasedArchitecture.Logistic_Regression import LogReg_single_signal

In [2]:
BASE_SEED = 42
set_seed(BASE_SEED)

In [3]:
dfSimAggNorm = pd.read_csv("../data/aggregated/simAggNorm.csv")
dfSimAgg = pd.read_csv("../data/aggregated/simAgg.csv")

In [4]:
summaryNorm = LogReg_single_signal(dfSimAggNorm)

========================================
ACTION UNIT:  AU01_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.670760   2   3   1   2
1   Bus14  0.312500  0.706831   4   1   2   9
2    Edu2  0.416667  0.673759   5   0   1   6
3    Ent5  0.666667  0.678443   5   3   1   3
4   Med15  0.588235  0.684666   3   7   5   2
5    Phi3  0.444444  0.706560   2   2   3   2
6    Pol2  0.444444  0.729509   4   4   4   6
7    Pol9  0.562500  0.691016   5   4   1   6
8  Tech10  0.600000  0.685048   6   3   1   5
9  Tech21  0.454545  0.728142   1   4   4   2
[[31 23]
 [43 37]]
========================================
ACTION UNIT:  AU02_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.875000  0.631511   4   3   1   0
1   Bus14  0.625000  0.671851   7   3   0   6
2    Edu2  0.583333  0.643423   6   1   0   5
3    Ent5  0.750000  0.629451   5   4   0   3
4   Med15  0.647059  0.658468   4   7   5   1
5    Phi3  0.555556  0.710474   2   3   2   2
6    Pol2  0.444444  0.762002   5   3   5   5
7    Pol9  0.625000  0.668583   6   4   1   5
8  Tech10  0.666667  0.645575   6   4   0   5
9  Tech21  0.272727  0.769231   1   2   6   2
[[34 20]
 [34 46]]
========================================
ACTION UNIT:  AU04_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.663582   3   2   2   1
1   Bus14  0.312500  0.739566   2   3   0  11
2    Edu2  0.416667  0.745873   5   0   1   6
3    Ent5  0.250000  0.734133   3   0   4   5
4   Med15  0.529412  0.673412   4   5   7   1
5    Phi3  0.777778  0.665021   4   3   2   0
6    Pol2  0.611111  0.674706   7   4   4   3
7    Pol9  0.562500  0.678341   8   1   4   3
8  Tech10  0.800000  0.668995   9   3   1   2
9  Tech21  0.181818  0.782309   0   2   6   3
[[23 31]
 [35 45]]
========================================
ACTION UNIT:  AU05_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.662948   2   3   1   2
1   Bus14  0.375000  0.715459   4   2   1   9
2    Edu2  0.500000  0.620184   6   0   1   5
3    Ent5  0.583333  0.651247   5   2   2   3
4   Med15  0.588235  0.763914   4   6   6   1
5    Phi3  0.777778  0.619213   3   4   1   1
6    Pol2  0.500000  0.692025   4   5   3   6
7    Pol9  0.562500  0.619572   5   4   1   6
8  Tech10  0.666667  0.614873   7   3   1   4
9  Tech21  0.727273  0.608709   0   8   0   3
[[37 17]
 [40 40]]
========================================
ACTION UNIT:  AU06_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.375000  0.728111   3   0   4   1
1   Bus14  0.562500  0.673655   9   0   3   4
2    Edu2  0.833333  0.658783  10   0   1   1
3    Ent5  0.750000  0.659700   6   3   1   2
4   Med15  0.529412  0.667641   1   8   4   4
5    Phi3  0.777778  0.657834   4   3   2   0
6    Pol2  0.500000  0.689899   8   1   7   2
7    Pol9  0.500000  0.738095   5   3   2   6
8  Tech10  0.333333  0.727305   3   2   2   8
9  Tech21  0.272727  0.703770   1   2   6   2
[[22 32]
 [30 50]]
========================================
ACTION UNIT:  AU07_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.669631   3   2   2   1
1   Bus14  0.562500  0.703377   8   1   2   5
2    Edu2  0.166667  0.738508   2   0   1   9
3    Ent5  0.750000  0.636386   6   3   1   2
4   Med15  0.705882  0.662637   1  11   1   4
5    Phi3  0.444444  0.704745   2   2   3   2
6    Pol2  0.666667  0.675950   9   3   5   1
7    Pol9  0.500000  0.728746   6   2   3   5
8  Tech10  0.533333  0.667521   6   2   2   5
9  Tech21  0.363636  0.763201   1   3   5   2
[[29 25]
 [36 44]]
========================================
ACTION UNIT:  AU09_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.693636   3   2   2   1
1   Bus14  0.625000  0.693122   8   2   1   5
2    Edu2  0.333333  0.722197   4   0   1   7
3    Ent5  0.500000  0.695526   4   2   2   4
4   Med15  0.411765  0.694025   2   5   7   3
5    Phi3  0.666667  0.694747   3   3   2   1
6    Pol2  0.333333  0.693721   3   3   5   7
7    Pol9  0.250000  0.697563   2   2   3   9
8  Tech10  0.333333  0.701224   5   0   4   6
9  Tech21  0.636364  0.693739   0   7   1   3
[[26 28]
 [46 34]]
========================================
ACTION UNIT:  AU12_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.250000  0.831450   2   0   4   2
1   Bus14  0.625000  0.676833   9   1   2   4
2    Edu2  0.666667  0.658556   8   0   1   3
3    Ent5  0.583333  0.662829   6   1   3   2
4   Med15  0.470588  0.660334   1   7   5   4
5    Phi3  0.555556  0.698205   1   4   1   3
6    Pol2  0.500000  0.697073   6   3   5   4
7    Pol9  0.562500  0.711080   7   2   3   4
8  Tech10  0.733333  0.669196  10   1   3   1
9  Tech21  0.636364  0.664474   2   5   3   1
[[24 30]
 [28 52]]

In [5]:
summaryNorm

,Action Unit,Accuracy (Balanced),Loss,precision_0,precision_1,recall_0,recall_1,f1_0,f1_1,macro_f1
1,AU02_r,0.602,0.681,0.500,0.697,0.630,0.575,0.557,0.630,0.594
3,AU05_r,0.593,0.663,0.481,0.702,0.685,0.500,0.565,0.584,0.574
7,AU12_r,0.547,0.687,0.462,0.634,0.444,0.650,0.453,0.642,0.547
5,AU07_r,0.544,0.694,0.446,0.638,0.537,0.550,0.487,0.591,0.539
0,AU01_r,0.518,0.697,0.419,0.617,0.574,0.462,0.484,0.529,0.506
4,AU06_r,0.516,0.691,0.423,0.610,0.407,0.625,0.415,0.617,0.516
2,AU04_r,0.494,0.701,0.397,0.592,0.426,0.562,0.411,0.577,0.494
6,AU09_r,0.453,0.698,0.361,0.548,0.481,0.425,0.413,0.479,0.446

In [6]:
summary = LogReg_single_signal(dfSimAgg)

========================================
ACTION UNIT:  AU01_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.500000  0.636703   1   3   1   3
1   Bus14  0.500000  0.658689   7   1   2   6
2    Edu2  0.416667  0.694776   5   0   1   6
3    Ent5  0.666667  0.660496   5   3   1   3
4   Med15  0.647059  0.671349   3   8   4   2
5    Phi3  0.555556  0.702693   0   5   0   4
6    Pol2  0.444444  0.758563   4   4   4   6
7    Pol9  0.562500  0.701645   5   4   1   6
8  Tech10  0.800000  0.573144  10   2   2   1
9  Tech21  0.727273  0.637238   0   8   0   3
[[38 16]
 [40 40]]
========================================
ACTION UNIT:  AU02_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.750000  0.622680   4   2   2   0
1   Bus14  0.687500  0.600557   9   2   1   4
2    Edu2  0.583333  0.597592   6   1   0   5
3    Ent5  0.666667  0.629353   4   4   0   4
4   Med15  0.588235  0.714386   4   6   6   1
5    Phi3  0.555556  0.710982   2   3   2   2
6    Pol2  0.444444  0.792122   5   3   5   5
7    Pol9  0.437500  0.718557   2   5   0   9
8  Tech10  0.733333  0.591021   8   3   1   3
9  Tech21  0.727273  0.626123   0   8   0   3
[[37 17]
 [36 44]]
========================================
ACTION UNIT:  AU04_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.750000  0.655438   4   2   2   0
1   Bus14  0.750000  0.659772  10   2   1   3
2    Edu2  0.916667  0.610560  11   0   1   0
3    Ent5  0.416667  0.705178   5   0   4   3
4   Med15  0.705882  0.666299   1  11   1   4
5    Phi3  0.666667  0.661655   3   3   2   1
6    Pol2  0.611111  0.670428   9   2   6   1
7    Pol9  0.312500  0.801487   0   5   0  11
8  Tech10  0.333333  0.747975   2   3   1   9
9  Tech21  0.272727  0.927325   3   0   8   0
[[28 26]
 [32 48]]
========================================
ACTION UNIT:  AU05_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.665737   2   3   1   2
1   Bus14  0.375000  0.719777   4   2   1   9
2    Edu2  0.416667  0.708092   5   0   1   6
3    Ent5  0.666667  0.667477   5   3   1   3
4   Med15  0.588235  0.796256   4   6   6   1
5    Phi3  0.777778  0.631750   3   4   1   1
6    Pol2  0.611111  0.682117   7   4   4   3
7    Pol9  0.562500  0.637173   5   4   1   6
8  Tech10  0.666667  0.609315   7   3   1   4
9  Tech21  0.727273  0.613231   0   8   0   3
[[37 17]
 [38 42]]
========================================
ACTION UNIT:  AU06_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.648903   4   1   3   0
1   Bus14  0.687500  0.641854   9   2   1   4
2    Edu2  0.833333  0.620779   9   1   0   2
3    Ent5  0.333333  0.752029   3   1   3   5
4   Med15  0.588235  0.669476   0  10   2   5
5    Phi3  0.222222  0.762653   0   2   3   4
6    Pol2  0.500000  0.718548   9   0   8   1
7    Pol9  0.437500  0.692057   3   4   1   8
8  Tech10  0.266667  0.809211   0   4   0  11
9  Tech21  0.818182  0.671769   1   8   0   2
[[33 21]
 [42 38]]
========================================
ACTION UNIT:  AU07_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.625000  0.685439   3   2   2   1
1   Bus14  0.312500  0.736381   4   1   2   9
2    Edu2  0.916667  0.683933  11   0   1   0
3    Ent5  0.250000  0.695870   3   0   4   5
4   Med15  0.352941  0.809611   5   1  11   0
5    Phi3  0.555556  0.691715   2   3   2   2
6    Pol2  0.500000  0.693078   2   7   1   8
7    Pol9  0.562500  0.689803   8   1   4   3
8  Tech10  0.533333  0.690067   6   2   2   5
9  Tech21  0.636364  0.688545   0   7   1   3
[[24 30]
 [36 44]]
========================================
ACTION UNIT:  AU09_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.500000  0.681290   2   2   2   2
1   Bus14  0.562500  0.667179   8   1   2   5
2    Edu2  0.583333  0.781953   7   0   1   4
3    Ent5  0.500000  0.682674   4   2   2   4
4   Med15  0.588235  0.681647   2   8   4   3
5    Phi3  0.444444  0.712466   1   3   2   3
6    Pol2  0.444444  0.698345   2   6   2   8
7    Pol9  0.625000  0.714504   8   2   3   3
8  Tech10  0.666667  0.616045   8   2   2   3
9  Tech21  0.727273  0.648124   0   8   0   3
[[34 20]
 [38 42]]
========================================
ACTION UNIT:  AU12_r
========================================
   Source  Accuracy      Loss  TP  TN  FP  FN
0    Art6  0.500000  0.689490   0   4   0   4
1   Bus14  0.750000  0.657898  10   2   1   3
2    Edu2  0.666667  0.646613   8   0   1   3
3    Ent5  0.583333  0.677838   7   0   4   1
4   Med15  0.588235  0.690868   0  10   2   5
5    Phi3  0.555556  0.686545   0   5   0   4
6    Pol2  0.611111  0.690444   7   4   4   3
7    Pol9  0.375000  0.688808   4   2   3   7
8  Tech10  0.266667  0.792698   0   4   0  11
9  Tech21  0.636364  0.685602   1   6   2   2
[[37 17]
 [43 37]]

In [7]:
summary

,Action Unit,Accuracy (Balanced),Loss,precision_0,precision_1,recall_0,recall_1,f1_0,f1_1,macro_f1
1,AU02_r,0.618,0.667,0.507,0.721,0.685,0.550,0.583,0.624,0.603
3,AU05_r,0.605,0.679,0.493,0.712,0.685,0.525,0.574,0.604,0.589
0,AU01_r,0.602,0.673,0.487,0.714,0.704,0.500,0.576,0.588,0.582
6,AU09_r,0.577,0.687,0.472,0.677,0.630,0.525,0.540,0.592,0.566
7,AU12_r,0.574,0.692,0.462,0.685,0.685,0.462,0.552,0.552,0.552
2,AU04_r,0.559,0.710,0.467,0.649,0.519,0.600,0.491,0.623,0.557
4,AU06_r,0.543,0.699,0.440,0.644,0.611,0.475,0.512,0.547,0.529
5,AU07_r,0.497,0.711,0.400,0.595,0.444,0.550,0.421,0.571,0.496