In [1]:
import pandas as pd
from src.configuration.config import set_seed, SEED
from src.utils.data import au_cols
from src.training.evaluation import full_test_evaluation_per_split
from src.configuration.config import LOCKED_CONFIG
from src.training.training import full_training_per_split
from src.MILArchitecture.AttentionMIL import AttentionMIL
import torch
import torch.nn as nn
from src.training.loaders import initialize_loaders_per_split
from src.utils.data import sources
from src.MILArchitecture.windows import initialize_all_bags
from sklearn.metrics import balanced_accuracy_score, classification_report
from src.MILArchitecture.full_pipelines import attention_based_mil_combination_comparison

In [2]:
df = pd.read_csv("../data/processed/combined.csv")

# Testing ALL eight Single Signals

In [3]:
summary_single_signals = attention_based_mil_combination_comparison(df, au_cols)

In [4]:
summary_single_signals = summary_single_signals.sort_values("bal. accuracy", ascending=False)
summary_single_signals

,au,loss,bal. accuracy,precision_0,precision_1,recall_0,recall_1,f1_0,f1_1
1,AU02_r,0.678007,0.559954,0.488889,0.640449,0.407407,0.7125,0.444444,0.674556
6,AU09_r,0.678225,0.548611,0.545455,0.625000,0.222222,0.8750,0.315789,0.729167
3,AU05_r,0.671638,0.492593,0.384615,0.592593,0.185185,0.8000,0.250000,0.680851
5,AU07_r,0.719458,0.486806,0.352941,0.589744,0.111111,0.8625,0.169014,0.700508
7,AU12_r,0.710709,0.445833,0.290323,0.563107,0.166667,0.7250,0.211765,0.633880
0,AU01_r,0.695597,0.436574,0.266667,0.557692,0.148148,0.7250,0.190476,0.630435
4,AU06_r,0.705670,0.417361,0.279070,0.538462,0.222222,0.6125,0.247423,0.573099
2,AU04_r,0.748692,0.392593,0.238095,0.521739,0.185185,0.6000,0.208333,0.558140

# Testing ALL AU Pairs

In [5]:
from itertools import combinations
au_pairs = list(combinations(au_cols, 2))

summary_pair_combinations = attention_based_mil_combination_comparison(df, au_pairs)

In [6]:
summary_pair_combinations

,au,loss,bal. accuracy,precision_0,precision_1,recall_0,recall_1,f1_0,f1_1
12,"(AU02_r, AU12_r)",0.704791,0.618981,0.581395,0.681319,0.462963,0.7750,0.515464,0.725146
8,"(AU02_r, AU05_r)",0.713285,0.609259,0.538462,0.682927,0.518519,0.7000,0.528302,0.691358
23,"(AU06_r, AU09_r)",0.679796,0.606944,0.600000,0.666667,0.388889,0.8250,0.471910,0.737430
0,"(AU01_r, AU02_r)",0.699102,0.591435,0.571429,0.656566,0.370370,0.8125,0.449438,0.726257
27,"(AU09_r, AU12_r)",0.695724,0.582407,0.586207,0.647619,0.314815,0.8500,0.409639,0.735135
9,"(AU02_r, AU06_r)",0.723895,0.569907,0.548387,0.640777,0.314815,0.8250,0.400000,0.721311
13,"(AU04_r, AU05_r)",0.658919,0.566667,0.529412,0.640000,0.333333,0.8000,0.409091,0.711111
11,"(AU02_r, AU09_r)",0.704765,0.563194,0.500000,0.641304,0.388889,0.7375,0.437500,0.686047
18,"(AU05_r, AU06_r)",0.697032,0.560417,0.514286,0.636364,0.333333,0.7875,0.404494,0.703911
6,"(AU01_r, AU12_r)",0.686466,0.547222,0.461538,0.634146,0.444444,0.6500,0.452830,0.641975
2,"(AU01_r, AU05_r)",0.703916,0.545370,0.520000,0.623853,0.240741,0.8500,0.329114,0.719577
10,"(AU02_r, AU07_r)",0.723569,0.529398,0.457143,0.616162,0.296296,0.7625,0.359551,0.681564
21,"(AU05_r, AU12_r)",0.697785,0.526620,0.464286,0.613208,0.240741,0.8125,0.317073,0.698925
16,"(AU04_r, AU09_r)",0.702924,0.519907,0.435897,0.610526,0.314815,0.7250,0.365591,0.662857
20,"(AU05_r, AU09_r)",0.705697,0.517361,0.444444,0.607477,0.222222,0.8125,0.296296,0.695187
5,"(AU01_r, AU09_r)",0.708158,0.505324,0.421053,0.600000,0.148148,0.8625,0.219178,0.707692
26,"(AU07_r, AU12_r)",0.716787,0.505093,0.416667,0.600000,0.185185,0.8250,0.256410,0.694737
19,"(AU05_r, AU07_r)",0.710408,0.505093,0.416667,0.600000,0.185185,0.8250,0.256410,0.694737
25,"(AU07_r, AU09_r)",0.680675,0.496528,0.375000,0.595238,0.055556,0.9375,0.096774,0.728155
3,"(AU01_r, AU06_r)",0.696407,0.495139,0.394737,0.593750,0.277778,0.7125,0.326087,0.647727
7,"(AU02_r, AU04_r)",0.733548,0.482407,0.377778,0.584270,0.314815,0.6500,0.343434,0.615385
24,"(AU06_r, AU12_r)",0.702409,0.479630,0.368421,0.583333,0.259259,0.7000,0.304348,0.636364
1,"(AU01_r, AU04_r)",0.740235,0.458565,0.291667,0.572727,0.129630,0.7875,0.179487,0.663158
4,"(AU01_r, AU07_r)",0.700380,0.452778,0.200000,0.571429,0.055556,0.8500,0.086957,0.683417
22,"(AU06_r, AU07_r)",0.738672,0.445602,0.305556,0.561224,0.203704,0.6875,0.244444,0.617978
14,"(AU04_r, AU06_r)",0.751388,0.439352,0.297297,0.556701,0.203704,0.6750,0.241758,0.610169
15,"(AU04_r, AU07_r)",0.755190,0.430093,0.277778,0.551020,0.185185,0.6750,0.222222,0.606742
17,"(AU04_r, AU12_r)",0.753397,0.414352,0.268293,0.537634,0.203704,0.6250,0.231579,0.578035

# Testing ALL AU-Triplets

In [7]:
au_triples = list(combinations(au_cols, 3))

summary_triple_combinations = attention_based_mil_combination_comparison(df, au_triples)

In [8]:
summary_triple_combinations

,au,loss,bal. accuracy,precision_0,precision_1,recall_0,recall_1,f1_0,f1_1
0,"(AU01_r, AU02_r, AU04_r)",0.757665,0.572917,0.545455,0.643564,0.333333,0.8125,0.413793,0.718232
31,"(AU02_r, AU06_r, AU09_r)",0.698890,0.571759,0.482759,0.657895,0.518519,0.6250,0.500000,0.641026
29,"(AU02_r, AU05_r, AU12_r)",0.695075,0.566204,0.500000,0.644444,0.407407,0.7250,0.448980,0.682353
35,"(AU02_r, AU09_r, AU12_r)",0.679280,0.560648,0.533333,0.634615,0.296296,0.8250,0.380952,0.717391
54,"(AU06_r, AU09_r, AU12_r)",0.724060,0.560417,0.514286,0.636364,0.333333,0.7875,0.404494,0.703911
52,"(AU06_r, AU07_r, AU09_r)",0.681624,0.552083,0.642857,0.625000,0.166667,0.9375,0.264706,0.750000
51,"(AU05_r, AU09_r, AU12_r)",0.688203,0.550926,0.487179,0.631579,0.351852,0.7500,0.408602,0.685714
1,"(AU01_r, AU02_r, AU05_r)",0.720552,0.550463,0.469388,0.635294,0.425926,0.6750,0.446602,0.654545
39,"(AU04_r, AU05_r, AU12_r)",0.678875,0.547917,0.486486,0.628866,0.333333,0.7625,0.395604,0.689266
21,"(AU02_r, AU04_r, AU05_r)",0.688427,0.544907,0.485714,0.626263,0.314815,0.7750,0.382022,0.692737
37,"(AU04_r, AU05_r, AU07_r)",0.714412,0.544676,0.475000,0.627660,0.351852,0.7375,0.404255,0.678161
6,"(AU01_r, AU04_r, AU05_r)",0.714422,0.541898,0.484848,0.623762,0.296296,0.7875,0.367816,0.696133
36,"(AU04_r, AU05_r, AU06_r)",0.689051,0.541898,0.484848,0.623762,0.296296,0.7875,0.367816,0.696133
11,"(AU01_r, AU05_r, AU06_r)",0.687530,0.541667,0.473684,0.625000,0.333333,0.7500,0.391304,0.681818
20,"(AU01_r, AU09_r, AU12_r)",0.682676,0.541435,0.465116,0.626374,0.370370,0.7125,0.412371,0.666667
28,"(AU02_r, AU05_r, AU09_r)",0.710567,0.538657,0.472222,0.622449,0.314815,0.7625,0.377778,0.685393
45,"(AU04_r, AU09_r, AU12_r)",0.729356,0.536111,0.500000,0.618182,0.222222,0.8500,0.307692,0.715789
10,"(AU01_r, AU04_r, AU12_r)",0.710345,0.535185,0.454545,0.622222,0.370370,0.7000,0.408163,0.658824
5,"(AU01_r, AU02_r, AU12_r)",0.725054,0.533102,0.500000,0.616071,0.203704,0.8625,0.289474,0.718750
26,"(AU02_r, AU05_r, AU06_r)",0.693753,0.529861,0.480000,0.614679,0.222222,0.8375,0.303797,0.708995
27,"(AU02_r, AU05_r, AU07_r)",0.721548,0.529630,0.466667,0.615385,0.259259,0.8000,0.333333,0.695652
38,"(AU04_r, AU05_r, AU09_r)",0.688465,0.526852,0.478261,0.612613,0.203704,0.8500,0.285714,0.712042
30,"(AU02_r, AU06_r, AU07_r)",0.769652,0.525926,0.441860,0.615385,0.351852,0.7000,0.391753,0.654971
23,"(AU02_r, AU04_r, AU07_r)",0.718376,0.522917,0.439024,0.612903,0.333333,0.7125,0.378947,0.658960
13,"(AU01_r, AU05_r, AU09_r)",0.709333,0.520370,0.448276,0.609524,0.240741,0.8000,0.313253,0.691892
33,"(AU02_r, AU07_r, AU09_r)",0.730296,0.514352,0.440000,0.605505,0.203704,0.8250,0.278481,0.698413
12,"(AU01_r, AU05_r, AU07_r)",0.725137,0.514120,0.433333,0.605769,0.240741,0.7875,0.309524,0.684783
22,"(AU02_r, AU04_r, AU06_r)",0.746733,0.513657,0.425000,0.606383,0.314815,0.7125,0.361702,0.655172
50,"(AU05_r, AU07_r, AU12_r)",0.706715,0.511111,0.428571,0.603774,0.222222,0.8000,0.292683,0.688172
43,"(AU04_r, AU07_r, AU09_r)",0.697106,0.511111,0.428571,0.603774,0.222222,0.8000,0.292683,0.688172
25,"(AU02_r, AU04_r, AU12_r)",0.707512,0.510417,0.418605,0.604396,0.333333,0.6875,0.371134,0.643275
16,"(AU01_r, AU06_r, AU09_r)",0.707500,0.507407,0.414634,0.602151,0.314815,0.7000,0.357895,0.647399
32,"(AU02_r, AU06_r, AU12_r)",0.689216,0.507176,0.413043,0.602273,0.351852,0.6625,0.380000,0.630952
2,"(AU01_r, AU02_r, AU06_r)",0.704200,0.505093,0.416667,0.600000,0.185185,0.8250,0.256410,0.694737
7,"(AU01_r, AU04_r, AU06_r)",0.724946,0.504398,0.410256,0.600000,0.296296,0.7125,0.344086,0.651429
4,"(AU01_r, AU02_r, AU09_r)",0.686394,0.501389,0.405405,0.597938,0.277778,0.7250,0.329670,0.655367
34,"(AU02_r, AU07_r, AU12_r)",0.707868,0.499074,0.400000,0.596491,0.148148,0.8500,0.216216,0.701031
47,"(AU05_r, AU06_r, AU09_r)",0.705159,0.497917,0.400000,0.595506,0.333333,0.6625,0.363636,0.627219
14,"(AU01_r, AU05_r, AU12_r)",0.688205,0.496065,0.388889,0.594828,0.129630,0.8625,0.194444,0.704082
24,"(AU02_r, AU04_r, AU09_r)",0.700452,0.495370,0.393939,0.594059,0.240741,0.7500,0.298851,0.662983
17,"(AU01_r, AU06_r, AU12_r)",0.693525,0.494676,0.395833,0.593023,0.351852,0.6375,0.372549,0.614458
3,"(AU01_r, AU02_r, AU07_r)",0.759375,0.492361,0.387097,0.592233,0.222222,0.7625,0.282353,0.666667
9,"(AU01_r, AU04_r, AU09_r)",0.704118,0.486111,0.375000,0.588235,0.222222,0.7500,0.279070,0.659341
55,"(AU07_r, AU09_r, AU12_r)",0.721408,0.480093,0.357143,0.584906,0.185185,0.7750,0.243902,0.666667
41,"(AU04_r, AU06_r, AU09_r)",0.740838,0.476157,0.369565,0.579545,0.314815,0.6375,0.340000,0.607143
46,"(AU05_r, AU06_r, AU07_r)",0.726820,0.475926,0.372549,0.578313,0.351852,0.6000,0.361905,0.588957
8,"(AU01_r, AU04_r, AU07_r)",0.711661,0.474074,0.333333,0.581818,0.148148,0.8000,0.205128,0.673684
19,"(AU01_r, AU07_r, AU12_r)",0.681676,0.470602,0.343750,0.578431,0.203704,0.7375,0.255814,0.648352
15,"(AU01_r, AU06_r, AU07_r)",0.707593,0.470139,0.357143,0.576087,0.277778,0.6625,0.312500,0.616279
18,"(AU01_r, AU07_r, AU09_r)",0.708128,0.465509,0.125000,0.579365,0.018519,0.9125,0.032258,0.708738
44,"(AU04_r, AU07_r, AU12_r)",0.712133,0.455556,0.272727,0.571429,0.111111,0.8000,0.157895,0.666667
48,"(AU05_r, AU06_r, AU12_r)",0.710762,0.454398,0.340426,0.563218,0.296296,0.6125,0.316832,0.586826
42,"(AU04_r, AU06_r, AU12_r)",0.731778,0.445833,0.290323,0.563107,0.166667,0.7250,0.211765,0.633880
49,"(AU05_r, AU07_r, AU09_r)",0.729004,0.436343,0.285714,0.555556,0.185185,0.6875,0.224719,0.614525
53,"(AU06_r, AU07_r, AU12_r)",0.711166,0.436343,0.285714,0.555556,0.185185,0.6875,0.224719,0.614525
40,"(AU04_r, AU06_r, AU07_r)",0.738995,0.423843,0.270270,0.546392,0.185185,0.6625,0.219780,0.598870

# Convert To LaTeX

In [9]:
summary_single_signals.to_latex(
    "../results/attention_based_mil/tables/single_signal_results.tex",
    index=True,
    float_format="%.3f"
)

summary_pair_combinations.to_latex(
    "../results/attention_based_mil/tables/pair_combination_results.tex",
    index=True,
    float_format="%.3f"
)

summary_triple_combinations.to_latex(
    "../results/attention_based_mil/tables/triple_combination_results.tex",
    index=True,
    float_format="%.3f"
)